### PR TITLE
Track when we had good data for monitors

### PR DESCRIPTION
**Pull request by Mr0grog**
Some monitors weren’t really stably reporting data until after a certain date, so record when we started having good data for each monitor and only record/report from after that date.

At the moment, this works by recording a `good_after` date in our monitor metadata JSON file. We avoid recording data before that date. We’ll also need to throw out existing data we have before that date.
- [x] Record `good_after` date for relevant monitors
- [x] Don’t record data in the event hook if the `good_after` condition is not met
- [x] Don’t record data in tasks if the `good_after` condition is not met
- [x] Remove old data that doesn’t match the `good_after` condition

### CODE REVIEW

**Comment by Mr0grog** [comment]
Grr, as @alanjosephwilliams noted in Slack, it looks like what we actually have is periods of bad data. So this probably needs to be flipped entirely so that we record an array of data ranges for bad data.

Probably something like:

``` json
"bad_dates": [
  ["2015-02-02T09:32:00", "2015-02-04T09:30:00"],
  ["2015-02-21T13:03:00", "2015-02-26T15:30:00"],
  …
]
```

Seem reasonable, @alanjosephwilliams @daguar @bensheldon ?

**Comment by Mr0grog** [comment]
Should those ranges be able to have a placeholder signifying “the beginning of all time” and “heat-death of the universe” for monitors that started bad/are not-yet-fixed? Or just use really ancient/far future dates?

**Comment by bensheldon** [comment]
In addition to blanket good/bad times, we should probably base our historical uptimes on ETLed Pingometer Events. We should rely on ETLed Events over webhook events because the webhook is inherently unreliable: in addition to going over the internet, it's easy to crash-out, as happened yesterday  when a slow Pingdom API caused the requests to Time out (this happened on both the Sinatra and Rails apps). 

So webhook for reporting contemprary current up/down-ness, but ETLed Event data for determining historical uptime.

Also, in addition to having blanket times, we should probably have an annotation field for incidents, as well as an "accepted/rejected" flag so that we can (more) easily document and filter out incidents if we know that they are not realsy.

**Comment by Mr0grog** [comment]
> So webhook for reporting contemprary current up/down-ness, but ETLed Event data for determining historical uptime.

I’m not sure there’s really a meaningful difference, though. Maybe what that really means is that we should be running the ETL tasks every so often via cron/scheduler.

> probably have an annotation field for incidents

:+1: x :100:

> an "accepted/rejected" flag so that we can (more) easily document and filter out incidents if we know that they are not realsy

Hmmm, not sure I’m getting this one (maybe just need more detail)

**Comment by Mr0grog** [comment]
But also, on uptimes: you’re right that we should be running them off our data, whether that’s coming in via webhook or ETL. Current process is left-behind from before we were tracking stuff appropriately ourselves. Also it’s a bit more work to synthesize those stats. <— new issue?

(Relatedly, maybe we should start ETL-ing checks, too, so we can get latency.)

**Comment by bensheldon** [comment]
> > an "accepted/rejected" flag so that we can (more) easily document and filter out incidents if we know that they are not realsy
> 
> Hmmm, not sure I’m getting this one (maybe just need more detail)

We just may need to tag certain events as "our fuckup; doesn't count" (because if we just delete them, they'll get re-created during the ETL process). So just something like an "accepted" flag (defaulted to true, but we can manually set to false if we discover the incident was caused by an issue on our end, rather than the WebPortal itself).

**Comment by bensheldon** [comment]
> But also, on uptimes: you’re right that we should be running them off our data, whether that’s coming in via webhook or ETL.

Yes. It would be _really_ awesome if @pingometer included the `event_id` in their webhook so that we could _super easily_ reconcile webhook events with events stored in their API. This would also be _way_ more reliable than our current method of `get webook -> get webhook's monitor -> record monitor's last event` which has some slackness in the relation between "webhook" and "event" because it's basically time-bound ("last event") rather than related on a strong event id.

**Comment by Mr0grog** [comment]
> because if we just delete them, they'll get re-created during the ETL process

That’s what the `bad_dates` field is there to address, though.

That said, it occurs to me that it might make sense to have incidents of “unknown” status (as opposed to down), since we can’t reliably say whether the site was up or down during that time. I guess that’s pretty similar to what you’re saying, though the semantics feel slightly better to me (at first glance at least). We may or may not surface those in charts.

**Comment by Mr0grog** [comment]
> It would be really awesome if @pingometer included the event_id in their webhook so that we could super easily reconcile webhook events with events stored in their API. This would also be way more reliable than our current method

We _could_ switch to the method used in the snapshots ETL task: https://github.com/codeforamerica/snap-it-up/blob/master/tasks/s3.rake#L27 Not perfect, but more accurate than just taking the last event.

**Comment by pingometer** [comment]
We'll include the "last_event" in the webhook - it'll get deployed today.
It makes total sense to do it this way - we're onboard.

**Comment by Mr0grog** [comment]
@pingometer: Awesome! That makes a lot more sense than the current set-up. What will this look like in terms of how it’s encoded?

**Comment by bensheldon** [comment]
> That’s what the bad_dates field is there to address, though.

I guess I don't like the idea of `bad_dates` because it's not really tied to the actual incidents and seems like it will be susceptible to typos or just lack of context (an array of dates, rather an a set of `bad_periods` objects that can be annotated/explained ) . Though this is probably just the difference between me doing my work on a relational database and you doing work on a non-relational database :smile:

**Comment by bensheldon** [comment]
@pingometer **_Yay!**_ Thank you! :icecream:

**Comment by Mr0grog** [comment]
> I guess I don't like the idea of bad_dates because it's not really tied to the actual incidents and seems like it will be susceptible to typos or just lack of context

Well… it can certainly be annotated if you think that’d be useful. It’s a lot more human-editable by someone other than you and me than having them log into the DB and edit the event :P

Further, I think we still need something like `bad_dates` or at least `good_after` because those time periods may have multiple events. There’s no 1:1 correspondence here. We could, alternatively, synthesize “unknown status” or “rejected” incidents from the bad dates (rather than using them to remove/ignore pingometer events).

**Comment by Mr0grog** [comment]
I guess I also don’t feel like we have anything approaching a stable and canonical DB/storage for metadata like this yet, excepting that JSON file.

**Comment by Mr0grog** [comment]
> We could, alternatively, synthesize “unknown status” or “rejected” incidents from the bad dates (rather than using them to remove/ignore pingometer events).

Or in addition to removing/ignoring pingometer events. I guess I’m warming up to your rejected incidents, even though I still like my naming better :)

(Side note: another reason I like `status` is that it gives us a way in the future to have incidents for things like “unstable” or “reduced performance” or something, where there is super high latency or intermittent request successes/failures. I might be trying to conflate too many things there, though.)

**Comment by pingometer** [comment]
@Mr0grog It's available in the webhooks now. Here's how it looks in the request body:

`monitor_last_event_id: 5511e97819jg74db32400fc5`

**Comment by Mr0grog** [comment]
Suuuuuuuuper janky, but it works, which we need for now.

**Pull request merged**
