### PR TITLE
Calculate from local data

### PR DESCRIPTION
**Pull request by Mr0grog**
So, in order to cut out bad data, we need to calculate from the local data we have cached. This branch does that, but it turns out our local data does not seem to match Pingometer at all. Would like to figure out what's going on before pushing this.

datadiff

FWIW, it's not too odd that the numbers might differ by a couple percentage points or less—we don't know exactly how Pingometer calculates uptime. BUT many differences are pretty radical, see CA, KS, NC.

### CODE REVIEW

**Comment by Mr0grog** [comment]
Ok, this should be good now.

The issue turned out to be that @pingometer does not reliably deliver the event hook. There are a number of times where our logs show no POSTS anywhere at all near the time of the event. Meaning we'd miss events entirely. When these were `UP` events, that means we'd effectively be recording a much longer downtime than actually happened.

This branch now changes the architecture to stop using the event hook and start ETL-ing events from Pingometer every two minutes. _(Side note: is that a good interval?)_

To do this, I'm adding [Qu](https://rubygems.org/gems/qu) for queuing/job handling and [Clockwork](https://rubygems.org/gems/clockwork) for scheduling. Qu can use mongodb as a backend, so there are no added external dependencies. If we were doing a lot more queued work, I'd say we should have a separate queuing system, but for our level of work, I think this is ok.

Also note that the same worker is doing scheduling and work. Since we don't do a lot of work, this is OK—and cheap :)

If we ever started doing more work, scaling is as simple as running `rake clockwork job_schedule.rb` for the `clock` process and `rake qu:work` for the worker processes. Everything should continue to function smoothly.

Other side note: I've made sure we only swallow snapshot exceptions when it's an actual timeout, so we'll start to see meaningful snapshot errors in logs/sentry after this. Specifically, our snapshots are currently broken because the CfA Browserstack account no longer has API access. We didn't know before because we were swallowing that error and treating it like a timeout. (see #53)

Once this is pushed to Heroku, we'll have to clear the DB and let the ETL job reload everything.

Planning to land this tomorrow AM unless people have Concerns.

**Comment by daguar** [comment]
Running off for the weekend, but looks good to me. I slacked this to you @Mr0grog already but if you can please dump a backup of the DB prior to clearing so we have something to refer to if we want to look back at this process.

**Comment by pingometer** [comment]
@Mr0grog Our default behavior is to automatically reattempt a webhook if a 4xx or 5xx status code is obtained (up to a maximum of three times). But, if a 2xx or 3xx status code is obtained, we don't reattempt to avoid hitting endpoints that are idempotent. If you don't see anything in the logs, it could be a timeout which does not trigger a reattempt (as of now).

**Comment by pingometer** [comment]
@Mr0grog We now reattempt a webhook for a timeout (in addition to a 4xx or 5xx error), as mentioned before.

**Comment by Mr0grog** [comment]
@pingometer thanks for that! However, I’m not seeing any requests corresponding to the times of some events. It could be I’m missing something, but since we’re running on Heroku, we should see logging from Heroku’s router regardless of what happened on our end (e.g. if we timed out). On Friday, we didn’t see any posts for these:

```
MONITOR                   STATUS   TIME                   STATE
------------------------  -------  --------------------   -----
54a7a085be653d4674bf5efa  :  1  :  2015-03-27 02:28:40Z  :  IL
54a7a085be653d4674bf5efa  :  0  :  2015-03-27 02:25:56Z  :  IL
54a79f09be653d4687bf5eee  :  0  :  2015-03-27 02:04:28Z  :  AZ
54a7a085be653d4674bf5efa  :  1  :  2015-03-27 01:55:49Z  :  IL
54a7a085be653d4674bf5efa  :  0  :  2015-03-27 01:04:32Z  :  IL
```

Though I no longer have those logs (we weren’t archiving them at the time and I didn’t think to download them). We have 7-day archiving now and I’m not seeing any posts correlating to these:

```
MONITOR                   STATUS   TIME                   STATE
------------------------  -------  --------------------   -----
54a713edbe653d45452a131d  :  0  :  2015-03-29T04:03:14Z  :  NH
54a79f09be653d4687bf5eee  :  0  :  2015-03-29T03:01:22Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-28T10:05:41Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-28T10:03:37Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-28T10:02:42Z  :  AZ
54a713edbe653d45452a131d  :  1  :  2015-03-28T10:02:30Z  :  NH
54a713edbe653d45452a131d  :  0  :  2015-03-28T04:02:14Z  :  NH
54a79f09be653d4687bf5eee  :  0  :  2015-03-28T04:01:20Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T18:40:41Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T18:40:12Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T14:37:16Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T14:34:35Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T14:29:28Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T14:27:35Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T14:23:22Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T14:21:09Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T14:16:19Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T14:14:28Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T14:09:19Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T14:06:15Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T13:22:26Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T13:19:30Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T13:11:00Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T13:08:36Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T12:46:46Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T12:44:28Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T12:40:59Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T12:38:27Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T12:34:20Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T12:32:02Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T12:24:27Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T12:21:10Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T12:16:16Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T12:10:58Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T12:05:49Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T12:02:12Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T11:37:20Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T11:31:10Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T11:26:17Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T11:23:21Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T10:52:27Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T10:47:10Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T10:40:59Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T10:36:35Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T10:05:46Z  :  AZ
54a713edbe653d45452a131d  :  1  :  2015-03-27T10:03:01Z  :  NH
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T09:59:35Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T09:47:02Z  :  AZ
54a79f09be653d4687bf5eee  :  0  :  2015-03-27T09:42:47Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T09:03:21Z  :  AZ
54a79f09be653d4687bf5eee  :  1  :  2015-03-27T09:03:21Z  :  AZ
54a713edbe653d45452a131d  :  0  :  2015-03-27T04:02:04Z  :  NH
```

…which shows a rather obvious pattern now that I’m looking at it.

Anyway! I don’t see _anything_ that looks like it might have been a request from Pingometer that corresponds to the times of those events, so I’m going to merge this PR and switch over to polling from the event hook. Happy to provide any additional data or feedback that might help you figure out what’s going on in a separate issue or via e-mail, though.

**Comment by Mr0grog** [comment]
@daguar Backups are at:

https://s3-us-west-2.amazonaws.com/snap-status-backup/2015-03-29/incidents.json
https://s3-us-west-2.amazonaws.com/snap-status-backup/2015-03-29/monitor_events.json
https://s3-us-west-2.amazonaws.com/snap-status-backup/2015-03-29/snapshots.json

There’s also a BSON dump in `/snap-status-backup/2015-03-29/dump/`

**Pull request merged**
